### ISSUE TITLE
powershell脚本版本限制

### ISSUE THREAD

**Issue by FunnyWolf** [chroblert/WindowsVulnScan#1]
ConvertTo-Json 这个函数在powershell2.0应该调用不了,比如window7或者win2008.是不是应该自行实现一个或者换个结构?

**Comment by chroblert** [comment]
确实，之前没考虑到这个问题 实现的话应该不复杂

**Comment by sharkocha** [comment]
ps脚本中的好几个函数在win7下自带的powershell中无法调用，自己试着写一个兼容版本的吧
