### ISSUE TITLE
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by xxsmile123** [chroblert/WindowsVulnScan#2]
========CVE-EXP-Check===============
    |       author:JC0o0l               |
    |       wechat:JC_SecNotes          |
    |       version:1.0                 |
    =====================================

Traceback (most recent call last):
  File "cve-check.py", line 277, in <module>
    KBResult = json.load(f)
  File "D:\python3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\python3\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

**Comment by chroblert** [comment]
文件要另存为utf-8格式
